/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRidersRouteImport } from './routes/admin.riders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as RestaurantIndexRouteImport } from './routes/restaurant.index'
import { Route as RestaurantMenuRouteImport } from './routes/restaurant.menu'
import { Route as RestaurantOrdersRouteImport } from './routes/restaurant.orders'
import { Route as RestaurantProfileRouteImport } from './routes/restaurant.profile'
import { Route as RestaurantsIndexRouteImport } from './routes/restaurants.index'
import { Route as RestaurantsIdRouteImport } from './routes/restaurants.$id'
import { Route as RiderIndexRouteImport } from './routes/rider.index'
import { Route as RiderDeliveriesRouteImport } from './routes/rider.deliveries'
import { Route as RiderEarningsRouteImport } from './routes/rider.earnings'
import { Route as RiderProfileRouteImport } from './routes/rider.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/admin/coupons',
  path: '/admin/coupons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/admin/restaurants',
  path: '/admin/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRidersRoute = AdminRidersRouteImport.update({
  id: '/admin/riders',
  path: '/admin/riders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIndexRoute = RestaurantIndexRouteImport.update({
  id: '/restaurant/',
  path: '/restaurant/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantMenuRoute = RestaurantMenuRouteImport.update({
  id: '/restaurant/menu',
  path: '/restaurant/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantOrdersRoute = RestaurantOrdersRouteImport.update({
  id: '/restaurant/orders',
  path: '/restaurant/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantProfileRoute = RestaurantProfileRouteImport.update({
  id: '/restaurant/profile',
  path: '/restaurant/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIndexRoute = RestaurantsIndexRouteImport.update({
  id: '/restaurants/',
  path: '/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantsIdRoute = RestaurantsIdRouteImport.update({
  id: '/restaurants/$id',
  path: '/restaurants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderIndexRoute = RiderIndexRouteImport.update({
  id: '/rider/',
  path: '/rider/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderDeliveriesRoute = RiderDeliveriesRouteImport.update({
  id: '/rider/deliveries',
  path: '/rider/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderEarningsRoute = RiderEarningsRouteImport.update({
  id: '/rider/earnings',
  path: '/rider/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiderProfileRoute = RiderProfileRouteImport.update({
  id: '/rider/profile',
  path: '/rider/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/profile': typeof RestaurantProfileRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/rider/deliveries': typeof RiderDeliveriesRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/restaurant/': typeof RestaurantIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/profile': typeof RestaurantProfileRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/rider/deliveries': typeof RiderDeliveriesRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin': typeof AdminIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/restaurant': typeof RestaurantIndexRoute
  '/restaurants': typeof RestaurantsIndexRoute
  '/rider': typeof RiderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/favorites': typeof FavoritesRoute
  '/login': typeof LoginRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/restaurants': typeof AdminRestaurantsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/riders': typeof AdminRidersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/orders/$id': typeof OrdersIdRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/orders': typeof RestaurantOrdersRoute
  '/restaurant/profile': typeof RestaurantProfileRoute
  '/restaurants/$id': typeof RestaurantsIdRoute
  '/rider/deliveries': typeof RiderDeliveriesRoute
  '/rider/earnings': typeof RiderEarningsRoute
  '/rider/profile': typeof RiderProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/restaurant/': typeof RestaurantIndexRoute
  '/restaurants/': typeof RestaurantsIndexRoute
  '/rider/': typeof RiderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/order-confirmation'
    | '/profile'
    | '/register'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/reviews'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/users'
    | '/orders/$id'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurant/profile'
    | '/restaurants/$id'
    | '/rider/deliveries'
    | '/rider/earnings'
    | '/rider/profile'
    | '/admin/'
    | '/orders/'
    | '/restaurant/'
    | '/restaurants/'
    | '/rider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/order-confirmation'
    | '/profile'
    | '/register'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/reviews'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/users'
    | '/orders/$id'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurant/profile'
    | '/restaurants/$id'
    | '/rider/deliveries'
    | '/rider/earnings'
    | '/rider/profile'
    | '/admin'
    | '/orders'
    | '/restaurant'
    | '/restaurants'
    | '/rider'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/login'
    | '/order-confirmation'
    | '/profile'
    | '/register'
    | '/admin/analytics'
    | '/admin/coupons'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/restaurants'
    | '/admin/reviews'
    | '/admin/riders'
    | '/admin/settings'
    | '/admin/users'
    | '/orders/$id'
    | '/restaurant/menu'
    | '/restaurant/orders'
    | '/restaurant/profile'
    | '/restaurants/$id'
    | '/rider/deliveries'
    | '/rider/earnings'
    | '/rider/profile'
    | '/admin/'
    | '/orders/'
    | '/restaurant/'
    | '/restaurants/'
    | '/rider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  FavoritesRoute: typeof FavoritesRoute
  LoginRoute: typeof LoginRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRidersRoute: typeof AdminRidersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  OrdersIdRoute: typeof OrdersIdRoute
  RestaurantMenuRoute: typeof RestaurantMenuRoute
  RestaurantOrdersRoute: typeof RestaurantOrdersRoute
  RestaurantProfileRoute: typeof RestaurantProfileRoute
  RestaurantsIdRoute: typeof RestaurantsIdRoute
  RiderDeliveriesRoute: typeof RiderDeliveriesRoute
  RiderEarningsRoute: typeof RiderEarningsRoute
  RiderProfileRoute: typeof RiderProfileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  RestaurantIndexRoute: typeof RestaurantIndexRoute
  RestaurantsIndexRoute: typeof RestaurantsIndexRoute
  RiderIndexRoute: typeof RiderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/admin/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/riders': {
      id: '/admin/riders'
      path: '/admin/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AdminRidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/': {
      id: '/restaurant/'
      path: '/restaurant'
      fullPath: '/restaurant/'
      preLoaderRoute: typeof RestaurantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/menu': {
      id: '/restaurant/menu'
      path: '/restaurant/menu'
      fullPath: '/restaurant/menu'
      preLoaderRoute: typeof RestaurantMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/orders': {
      id: '/restaurant/orders'
      path: '/restaurant/orders'
      fullPath: '/restaurant/orders'
      preLoaderRoute: typeof RestaurantOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/profile': {
      id: '/restaurant/profile'
      path: '/restaurant/profile'
      fullPath: '/restaurant/profile'
      preLoaderRoute: typeof RestaurantProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/': {
      id: '/restaurants/'
      path: '/restaurants'
      fullPath: '/restaurants/'
      preLoaderRoute: typeof RestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurants/$id': {
      id: '/restaurants/$id'
      path: '/restaurants/$id'
      fullPath: '/restaurants/$id'
      preLoaderRoute: typeof RestaurantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/': {
      id: '/rider/'
      path: '/rider'
      fullPath: '/rider/'
      preLoaderRoute: typeof RiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/deliveries': {
      id: '/rider/deliveries'
      path: '/rider/deliveries'
      fullPath: '/rider/deliveries'
      preLoaderRoute: typeof RiderDeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/earnings': {
      id: '/rider/earnings'
      path: '/rider/earnings'
      fullPath: '/rider/earnings'
      preLoaderRoute: typeof RiderEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rider/profile': {
      id: '/rider/profile'
      path: '/rider/profile'
      fullPath: '/rider/profile'
      preLoaderRoute: typeof RiderProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  FavoritesRoute: FavoritesRoute,
  LoginRoute: LoginRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRidersRoute: AdminRidersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  OrdersIdRoute: OrdersIdRoute,
  RestaurantMenuRoute: RestaurantMenuRoute,
  RestaurantOrdersRoute: RestaurantOrdersRoute,
  RestaurantProfileRoute: RestaurantProfileRoute,
  RestaurantsIdRoute: RestaurantsIdRoute,
  RiderDeliveriesRoute: RiderDeliveriesRoute,
  RiderEarningsRoute: RiderEarningsRoute,
  RiderProfileRoute: RiderProfileRoute,
  AdminIndexRoute: AdminIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  RestaurantIndexRoute: RestaurantIndexRoute,
  RestaurantsIndexRoute: RestaurantsIndexRoute,
  RiderIndexRoute: RiderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
